# Generated by Django 5.2.6 on 2025-09-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
